---
{{- if .Values.secretstore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}{{ .Values.canary.suffix }}
  labels: ### These are the labels that you are using for your other resources.
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secrets-manager{{ .Values.canary.suffix }}
    kind: SecretStore
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: {{ .Values.secret.name }}
        property: MONGODB_URI
    - secretKey: LOGGING_ELASTIC_SENSITIVE_URI
      remoteRef:
        key: {{ .Values.secret.name }}
        property: LOGGING_ELASTIC_SENSITIVE_URI
    - secretKey: CLIENT_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: {{ .Values.secret.name }}
        property: CLIENT_SECRET
    - secretKey: ORDER_TRACKER_CLIENT_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: ORDER_TRACKER_CLIENT_ID
    - secretKey: ORDER_TRACKER_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.secret.name }}
        property: ORDER_TRACKER_CLIENT_SECRET
    - secretKey: WEBEX_ACCESS_TOKEN
      remoteRef:
        key: {{ .Values.secret.name }}
        property: WEBEX_ACCESS_TOKEN
    - secretKey: WEBEX_ONESHOP_BUSINESS_FAILURE_ALERT_CHANNEL_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: WEBEX_ONESHOP_BUSINESS_FAILURE_ALERT_CHANNEL_ID
    - secretKey: WEBEX_ONSHOP_TECHNICAL_FAILURE_ALERT_CHANNEL_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: WEBEX_ONSHOP_TECHNICAL_FAILURE_ALERT_CHANNEL_ID
    - secretKey: WEBEX_ONEAPP_BUSINESS_FAILURE_ALERT_CHANNEL_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: WEBEX_ONEAPP_BUSINESS_FAILURE_ALERT_CHANNEL_ID
    - secretKey: WEBEX_ONEAPP_TECHNICAL_FAILURE_ALERT_CHANNEL_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: WEBEX_ONEAPP_TECHNICAL_FAILURE_ALERT_CHANNEL_ID
    - secretKey: WEBEX_MAVI_BUSINESS_FAILURE_ALERT_CHANNEL_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: WEBEX_MAVI_BUSINESS_FAILURE_ALERT_CHANNEL_ID
    - secretKey: WEBEX_MAVI_TECHNICAL_FAILURE_ALERT_CHANNEL_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: WEBEX_MAVI_TECHNICAL_FAILURE_ALERT_CHANNEL_ID
    - secretKey: WEBEX_MPF_TECHNICAL_FAILURE_ALERT_CHANNEL_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: WEBEX_MPF_TECHNICAL_FAILURE_ALERT_CHANNEL_ID
    - secretKey: OPERATE_CLIENT_ID
      remoteRef:
        key: {{ .Values.secret.name }}
        property: OPERATE_CLIENT_ID
    - secretKey: OPERATE_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.secret.name }}
        property: OPERATE_CLIENT_SECRET
    - secretKey: POM_SECRET_KEY
      remoteRef:
        key: {{ .Values.secret.name }}
        property: POM_SECRET_KEY
  {{- end }}
