{{- if .Values.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.service.name }}{{ .Values.canary.suffix }}
  labels:
    deploymentName: {{ .Values.service.name }}{{ .Values.canary.suffix }}
    dot.de/service: {{ .Chart.Name }}
    dot.de/team: {{ .Values.team.name }}

spec:
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  pollingInterval:  {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  scaleTargetRef:
    name: {{ .Values.service.name }}{{ .Values.canary.suffix }}
  triggers:
    - type: prometheus
      metadata:
        metricName: rate_http_server_requests_seconds_count
        metricType: AverageValue
        query: sum(rate(http_server_requests_seconds_count{namespace="{{ .Release.Namespace }}"}[1m]))
        serverAddress: http://victoria-metrics-victoria-metrics-cluster-vmselect.victoria-metrics.svc.cluster.local:8481/select/999/prometheus
        threshold: "{{ .Values.keda.threshold }}"
{{- end }}
