ingress:
  host: "pom-new-acquisition-mobile-process.oneapp.uat.hal.telekom.de"
environment:
  name: uat
  replicas:
    quantity: 1
  resources:
    java:
      xmx: 2G
      xms: 1G
    jaeger:
    requests:
      memory: "2Gi"
      cpu: "2"
    limits:
      memory: "3Gi"
      cpu: "3"
serviceAccount:
  enabled: true
  name: pom-new-acquisition-mobile-process-uat
  roleARN: arn:aws:iam::274765082782:role/pom-new-acquisition-mobile-process-uat
secret:
  enabled: true
  name: oneapp-pom-new-acquisition-mobile-process-uat
  arn : arn:aws:secretsmanager:eu-central-1:274765082782:secret:oneapp-pom-new-acquisition-mobile-process-uat-y6qTbZ
secretstore:
  enabled: true
pullsecret:
  enabled: true
  name: oneapp-pull-secret-v2
rbac:
  enabled: false
profiles:
  active: uat
dynatrace:
  enabled: true
  annotations:
    appNameDarwin: "MMA_2.0(D)"
    operationMode: "Development"
  labels:
    appNameDarwin: "MMA_2.0"
    operationMode: "Development"
# Tracing Config values #########################
tracing:
  enabled: true
  sampling:
    probability: 1.0
zipkin:
  tracing:
    endpoint: https://collector-zipkin-http-drax-guardians.qa.dhei.telekom.de:443/api/v2/spans
###############################################################
# Apps log enabling
###############################################################
app:
  logging:
    sensitive: true
    json: true
    maskAll: true
    maskedUri: true
    maskedParams: searchParam
    maskedHeaders: authorization, x-user-authentication
keda:
  enabled: false
  minReplicaCount: 3
  maxReplicaCount: 8
  pollingInterval: 15
  cooldownPeriod: 300
  threshold: 8
###############################################################
# Mongo Db Configuration
###############################################################
mongodb:
  db: pom-new-acquisition-mobile-process-uat
  isLocal: false
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
######## APPLICATION Rover SECURITY ########
security:
  oauth2:
    resourceserver:
      jwt:
        issuerUri: https://stargate.qa.dhei.telekom.de/auth/realms/cit2
        jwkSetUri: https://stargate.qa.dhei.telekom.de/auth/realms/cit2/protocol/openid-connect/certs
    client:
      registration:
        stargateClient:
          authGrantType: client_credentials
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          provider: stargate-client
      orderTrackerClient:
        authorizationGrantType: client_credentials
        clientId: ${ORDER_TRACKER_CLIENT_ID}
        clientSecret: ${ORDER_TRACKER_CLIENT_SECRET}
        provider: order-tracker-client
        registrationId: order-tracker-client
      provider:
        stargateClient:
          tokenUri: https://iris.qa.dhei.telekom.de/auth/realms/cit2/protocol/openid-connect/token
          tokenExpirationThreshold: 60
          reverseToken: false
        orderTrackerClient:
          tokenUri: https://eshop-oneshop-api.uat.eshop.yo-digital.com/gateway/eshop/openid-connect/v1/token
          tokenExpirationThreshold: 60
          reverseToken: false
# feign clients properties ######################
apiClients:
  eventStore:
    basePath: https://stargate.qa.dhei.telekom.de/cit2/dot/eventstore/v1/
    authorizationInterceptorBean: starGateAuthInjector
    loggerBean: feignLogger
  carmenPartyManagement:
    basePath: https://stargate.qa.dhei.telekom.de/cit2/digihu-mob/PartyManagement/v1
    authorizationInterceptorBean: starGateAuthInjector
    loggerBean: feignLogger
  carmenProductInventoryManagement:
    basePath: https://stargate.qa.dhei.telekom.de/cit2/digihu-mob/ProductInventoryManagement/v1/
    authorizationInterceptorBean: starGateAuthInjector
    loggerBean: feignLogger
  orderTrackerDPS:
    basePath: https://eshop-oneshop-api.uat.eshop.yo-digital.com/gateway/eshop/productOrdering/v3
    authorizationInterceptorBean: orderTrackerDPSAuthInjector
    loggerBean: feignLogger
  crmRouting:
    basePath: https://stargate.qa.dhei.telekom.de/cit2/digihu-mob/CrmRouting/v1
    name: crmrouting-client
  eSimActivationProductOrder:
    basePath: https://stargate.qa.dhei.telekom.de/cit2/digihu-mob/esim-activation-product-order/api/v1
    authorizationInterceptorBean: starGateAuthInjector
    loggerBean: feignLogger
################### CAMUNDA PROPERTIES ##############
camunda:
  processId: pom-new-mobile-acquisition-business-process
  logger:
    enabled: true
    enableMasking: true
    consoleLogging: true
    consoleLoggerStyle: JSON
    enablePrettyPrint: false
    fieldPath:
      correlationId: "variables.headers.x-request-tracking-id"
      channelId: "variables.productOrder.channel.id"
    maskedFields:
      -  de.telekom.pom.businessprocess.productordering.model.RelatedPartyRef:id?role=owner
      -  de.telekom.pom.businessprocess.productordering.model.TargetScope:id?entityBaseType=Product
    maskedHeaders:
      - authorization
    filter:
      excludedPaths:
        - /new-mobile-acquisition/v1/actuator
        - /new-mobile-acquisition/v1/swagger-ui
        - /new-mobile-acquisition/v1/v3/api-docs
        - /new-mobile-acquisition/v1/v2/api-docs
        - /new-mobile-acquisition/v1/api-docs
        - /new-mobile-acquisition/v1/error
    feign:
      loggerType: SENSITIVE
      consoleLogging: false
  operate:
    operateUrl: https://operate.oneapp.uat.hal.telekom.de
    clientId: ${OPERATE_CLIENT_ID}
    clientSecret: ${OPERATE_CLIENT_SECRET}
    keycloakUrl: https://keycloak.oneapp.dev.hal.telekom.de
    keycloakRealm: camunda-platform

# Zeebe gateway properties ######################
zeebe:
  client:
    broker:
      gatewayAddress: camunda-platform-zeebe-gateway.camunda.svc.cluster.local:26500
    security:
      plaintext: true
    worker:
      thread: 5
######################################
eiMessage:
  timeLeft : 49999
  priority : 4
  sender : sndr:tmd.crm.omsoe.architecture.OMSOE:OE
orderTrackerDPS:
  enabled : true
retryTiming:
  timeInMinutes : false
  firstRetryTime: 30
  secondRetryTime: 20
  thirdRetryTime: 15
  fourthRetryTime: 10
  fifthRetryTime: 5
################ Grafana Alerts Rule ######################
rules:
  enabled: true
  spec:
    - alert: ResponseTimeAlert
      annotations:
        description: "Service {{ $labels.service }} has a high response time in the last 1m"
        summary: High Response Time.
      expr: sum(irate(http_server_requests_seconds_sum{namespace="{{ .Release.Namespace }}", service="{{ .Values.service.name }}{{ .Values.canary.suffix }}"}[5m])) / sum(irate(http_server_requests_seconds_count{namespace="{{ .Release.Namespace }}", service="{{ .Values.service.name }}{{ .Values.canary.suffix }}"}[5m])) > 1
      interval: 1m
      labels:
        severity: warning
        team: Technocrats
    - alert: ErrorRate
      annotations:
        description: "Service {{ $labels.service }} has a high errors percentage in the last 1m"
        summary: High Error Percentage.
      expr: (sum(increase(http_server_requests_seconds_count{namespace="{{ .Release.Namespace }}", service="{{ .Values.service.name }}{{ .Values.canary.suffix }}", uri!~"(.*actuator.*|.*swagger-ui.*|root)", status!~"[2-3].*"}[5m])) / sum(increase(http_server_requests_seconds_count{namespace="{{ .Release.Namespace }}", service="{{ .Values.service.name }}{{ .Values.canary.suffix }}", uri!~"(.*actuator.*|.*swagger-ui.*|root)"}[5m])) * 100) > 5
      interval: 1m
      labels:
        severity: critical
        team: Technocrats
    - alert: MemoryUsage
      annotations:
        description: "Service {{ $labels.service }} memory consumption is >= 80%"
        summary: High Memory Consumption.
      expr: max(sum(container_memory_working_set_bytes{job="kubelet", metrics_path="/metrics/cadvisor", namespace="{{ .Release.Namespace }}", service="{{ .Values.service.name }}{{ .Values.canary.suffix }}", container!="", image!=""}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace="{{ .Release.Namespace }}", service="{{ .Values.service.name }}{{ .Values.canary.suffix }}"}) by (pod)) > 0.8
      interval: 1m
      labels:
        severity: warning
        team: Technocrats
    - alert: CpuUsage
      annotations:
        description: "Service {{ $labels.service }} CPU consumption is >= 80%"
        summary: High CPU Consumption.
      expr: max(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="{{ .Release.Namespace }}", service="{{ .Values.service.name }}{{ .Values.canary.suffix }}"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace="{{ .Release.Namespace }}", service="{{ .Values.service.name }}{{ .Values.canary.suffix }}"}) by (pod)) > 0.8
      interval: 1m
      labels:
        severity: warning
        team: Technocrats
    - alert: Heeap usage
      annotations:
        description: 'Pom New Mobile Acquisition Process heap usage is over 90%.'
        summary: Heeap usage
      expr: sum(jvm_memory_used_bytes{namespace="{{ .Release.Namespace }}", area="heap"})*100/sum(jvm_memory_max_bytes{namespace="{{ .Release.Namespace }}", area="heap"}) > 90
      for: 5m
      labels:
        severity: warning
        team: Technocrats
encryption:
  secretKey: ${POM_SECRET_KEY}
